FROM mcr.microsoft.com/playwright

# prepare install

RUN apt-get update && apt-get install -y git curl ssh ca-certificates

# === INSTALL Google Chrome ===
RUN curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
RUN apt-get update -y \
 && apt-get install -y --no-install-recommends google-chrome-stable xvfb fonts-vlgothic

# === INSTALL Edge ===
RUN curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-beta.list
RUN apt-get update -y \
 && apt-get install -y --no-install-recommends microsoft-edge-beta


User pwuser

WORKDIR /home/pwuser/app
